theme: jekyll-theme-minimal
title: Elisabeth's Website
description: Fun facts about me! 
#Favorite Places to eat in San Diego#
1. **Bahn Thai** (4646 Park Blvd, San Diego, CA 92116)
  1. Tasty little thai joint - my favorite is the yellow curry!
